#ifndef DOCKING_RESOURCE_H
#define DOCKING_RESOURCE_H

#define IDD_CONTAINER_DLG 6000
#define IDC_TAB_CONT 6001
#define IDC_CLIENT_TAB 6002
#define IDC_BTN_CAPTION 6003

#define IDD_PLUGIN_DLG 6004
#define IDC_EDIT_CONFIGURATION 6005

#define IDM 40000
#define IDM_VIEW_GOTO_ANOTHER_VIEW (IDM + 1)
#define IDM_VIEW_CLONE_TO_ANOTHER_VIEW (IDM + 2)
#define IDM_VIEW_GOTO_NEW_INSTANCE (IDM + 3)
#define IDM_VIEW_LOAD_IN_NEW_INSTANCE (IDM + 4)

#define IDM_TOOL (IDM + 8500)
#define IDM_TOOL_MD5_GENERATE (IDM_TOOL + 1)
#define IDM_TOOL_MD5_GENERATEFROMFILE (IDM_TOOL + 2)
#define IDM_TOOL_MD5_GENERATEINTOCLIPBOARD (IDM_TOOL + 3)
#define IDM_TOOL_SHA256_GENERATE (IDM_TOOL + 4)
#define IDM_TOOL_SHA256_GENERATEFROMFILE (IDM_TOOL + 5)
#define IDM_TOOL_SHA256_GENERATEINTOCLIPBOARD (IDM_TOOL + 6)

#endif // DOCKING_RESOURCE_H