#ifndef NOTEPAD_PLUS_MSGS_H
#define NOTEPAD_PLUS_MSGS_H

#include <windows.h>

#define NOTEPAD_PLUS_USER (WM_USER + 1000)
#define NPPM_GETCURRENTSCINTILLA (NOTEPAD_PLUS_USER + 4)
#define NPPM_GETFULLCURRENTPATH (NOTEPAD_PLUS_USER + 25)
#define NPPM_GETCURRENTDIRECTORY (NOTEPAD_PLUS_USER + 22)
#define NPPM_GETCURRENTFILENAME (NOTEPAD_PLUS_USER + 23)
#define NPPM_GETCURRENTLANGTYPE (NOTEPAD_PLUS_USER + 5)
#define NPPM_SETCURRENTLANGTYPE (NOTEPAD_PLUS_USER + 6)
#define NPPM_GETNBOPENFILES (NOTEPAD_PLUS_USER + 7)
#define NPPM_GETOPENFILENAMES (NOTEPAD_PLUS_USER + 8)
#define NPPM_MODELESSDIALOG (NOTEPAD_PLUS_USER + 12)
#define NPPM_GETNBSESSIONFILES (NOTEPAD_PLUS_USER + 13)
#define NPPM_GETSESSIONFILES (NOTEPAD_PLUS_USER + 14)
#define NPPM_SAVESESSION (NOTEPAD_PLUS_USER + 15)
#define NPPM_SAVECURRENTSESSION (NOTEPAD_PLUS_USER + 16)
#define NPPM_GETOPENFILENAMESPRIMARY (NOTEPAD_PLUS_USER + 17)
#define NPPM_GETOPENFILENAMESSECOND (NOTEPAD_PLUS_USER + 18)
#define NPPM_CREATESCINTILLAHANDLE (NOTEPAD_PLUS_USER + 20)
#define NPPM_DESTROYSCINTILLAHANDLE (NOTEPAD_PLUS_USER + 21)
#define NPPM_GETCURRENTWORD (NOTEPAD_PLUS_USER + 24)
#define NPPM_GETNPPDIRECTORY (NOTEPAD_PLUS_USER + 26)
#define NPPM_GETFILENAMEATCURSOR (NOTEPAD_PLUS_USER + 27)
#define NPPM_GETCURRENTLINE (NOTEPAD_PLUS_USER + 28)
#define NPPM_GETCURRENTCOLUMN (NOTEPAD_PLUS_USER + 29)
#define NPPM_GETNPPFULLFILEPATH (NOTEPAD_PLUS_USER + 30)
#define NPPM_MSGTOPLUGIN (NOTEPAD_PLUS_USER + 31)
#define NPPM_MENUCOMMAND (NOTEPAD_PLUS_USER + 48)
#define NPPM_TRIGGERNPSCOMMAND (NOTEPAD_PLUS_USER + 49)
#define NPPM_NPPM_EXECCOMMAND (NOTEPAD_PLUS_USER + 50)
#define NPPM_DMMREGASDCKDLG (NOTEPAD_PLUS_USER + 33)
#define NPPM_DMMSHOW (NOTEPAD_PLUS_USER + 34)
#define NPPM_DMMHIDE (NOTEPAD_PLUS_USER + 35)
#define NPPM_DMMUPDATEDISPINFO (NOTEPAD_PLUS_USER + 36)
#define NPPM_GETEDITORDEFAULTBACKGROUNDCOLOR (NOTEPAD_PLUS_USER + 37)
#define NPPM_GETEDITORDEFAULTFOREGROUNDCOLOR (NOTEPAD_PLUS_USER + 38)
#define NPPM_SETSMOOTHFONT (NOTEPAD_PLUS_USER + 39)
#define NPPM_SETEDITORBORDEREDGE (NOTEPAD_PLUS_USER + 40)
#define NPPM_GETEDITORBORDEREDGE (NOTEPAD_PLUS_USER + 41)
#define NPPM_GETLINENUMBERWIDTHMODE (NOTEPAD_PLUS_USER + 42)
#define NPPM_SETLINENUMBERWIDTHMODE (NOTEPAD_PLUS_USER + 43)
#define NPPM_GETLINENUMBERWIDTH (NOTEPAD_PLUS_USER + 44)
#define NPPM_SETLINENUMBERWIDTH (NOTEPAD_PLUS_USER + 45)
#define NPPM_GETCURRENTVIEW (NOTEPAD_PLUS_USER + 46)
#define NPPM_SETCURRENTVIEW (NOTEPAD_PLUS_USER + 47)
#define NPPM_GETCURRENTBUFFERID (NOTEPAD_PLUS_USER + 60)
#define NPPM_RELOADBUFFERID (NOTEPAD_PLUS_USER + 61)
#define NPPM_GETFULLPATHFROMBUFFERID (NOTEPAD_PLUS_USER + 62)
#define NPPM_GETBUFFERIDFROMPOS (NOTEPAD_PLUS_USER + 63)
#define NPPM_GETBUFFERIDFROMPATH (NOTEPAD_PLUS_USER + 65)
#define NPPM_GETBUFFERLANGTYPE (NOTEPAD_PLUS_USER + 66)
#define NPPM_SETBUFFERLANGTYPE (NOTEPAD_PLUS_USER + 67)
#define NPPM_GETBUFFERENCODING (NOTEPAD_PLUS_USER + 68)
#define NPPM_SETBUFFERENCODING (NOTEPAD_PLUS_USER + 69)
#define NPPM_GETBUFFERFORMAT (NOTEPAD_PLUS_USER + 70)
#define NPPM_SETBUFFERFORMAT (NOTEPAD_PLUS_USER + 71)
#define NPPM_HIDETABBAR (NOTEPAD_PLUS_USER + 72)
#define NPPM_ISTABBARHIDDEN (NOTEPAD_PLUS_USER + 73)
#define NPPM_HIDEMENU (NOTEPAD_PLUS_USER + 74)
#define NPPM_ISMENUHIDDEN (NOTEPAD_PLUS_USER + 75)
#define NPPM_HIDESTATUSBAR (NOTEPAD_PLUS_USER + 76)
#define NPPM_ISSTATUSBARHIDDEN (NOTEPAD_PLUS_USER + 77)
#define NPPM_GETSHORTCUTBYCMDID (NOTEPAD_PLUS_USER + 78)
#define NPPM_DOOPEN (NOTEPAD_PLUS_USER + 79)
#define NPPM_SAVECURRENTFILEAS (NOTEPAD_PLUS_USER + 80)
#define NPPM_GETCURRENTNATIVELANGENCODING (NOTEPAD_PLUS_USER + 81)
#define NPPM_ALLOCATESUPPORTED (NOTEPAD_PLUS_USER + 82)
#define NPPM_ALLOCATECMDID (NOTEPAD_PLUS_USER + 83)
#define NPPM_ALLOCATEMARKER (NOTEPAD_PLUS_USER + 84)
#define NPPM_GETLANGUAGENAME (NOTEPAD_PLUS_USER + 85)
#define NPPM_GETLANGUAGEDESC (NOTEPAD_PLUS_USER + 86)
#define NPPM_SHOWDOCLIST (NOTEPAD_PLUS_USER + 87)
#define NPPM_ISDOCLISTSHOWN (NOTEPAD_PLUS_USER + 88)
#define NPPM_GETAPPDATAPLUGINSALLOWED (NOTEPAD_PLUS_USER + 89)

#define MAIN_VIEW 0
#define SUB_VIEW 1

enum LangType {
    L_TEXT, L_PHP, L_C, L_CPP, L_CS, L_OBJC, L_JAVA, L_RC,
    L_HTML, L_XML, L_MAKEFILE, L_PASCAL, L_BATCH, L_INI, L_ASCII, L_USER,
    L_ASP, L_SQL, L_VB, L_JS, L_CSS, L_PERL, L_PYTHON, L_LUA,
    L_TEX, L_FORTRAN, L_BASH, L_FLASH, L_NSIS, L_TCL, L_LISP, L_SCHEME,
    L_ASM, L_DIFF, L_PROPS, L_PS, L_RUBY, L_SMALLTALK, L_VHDL, L_KIX, L_AU3,
    L_CAML, L_ADA, L_VERILOG, L_MATLAB, L_HASKELL, L_INNO, L_SEARCHRESULT,
    L_CMAKE, L_YAML, L_COBOL, L_GUI4CLI, L_D, L_POWERSHELL, L_R, L_JSP,
    L_COFFEESCRIPT, L_JSON, L_JAVASCRIPT, L_FORTRAN_77, L_BAANC, L_SREC,
    L_IHEX, L_TEHEX, L_SWIFT,
    L_ASN1, L_AVS, L_BLITZBASIC, L_PUREBASIC, L_FREEBASIC, L_CSOUND,
    L_ERLANG, L_ESCRIPT, L_FORTH, L_LATEX, L_MMIXAL, L_NIMROD, L_NNCRONTAB,
    L_OSCRIPT, L_REBOL, L_REGISTRY, L_RUST, L_SPICE, L_TXT2TAGS, L_VISUALPROLOG,
    L_TYPESCRIPT, L_JSON5, L_MSSQL, L_GDSCRIPT, L_HOLLYWOOD,
    L_EXTERNAL = 80
};

enum winVer {
    WV_UNKNOWN, WV_WIN32S, WV_95, WV_98, WV_ME, WV_NT, WV_W2K,
    WV_XP, WV_S2003, WV_XPX64, WV_VISTA, WV_WIN7, WV_WIN8, WV_WIN81, WV_WIN10
};

#endif // NOTEPAD_PLUS_MSGS_H